AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Tekbyte-Service-Deployment-Descriptor

Parameters:
  Stage:
    Type: String
    Description: test Stage name to deploy resources to
    AllowedValues:
      - dev
      - prod

Globals:
  Function:
    Runtime: java11
    MemorySize: 1024
    Timeout: 20
    AutoPublishAlias: !Ref Stage
    Handler: org.springframework.cloud.function.adapter.aws.FunctionInvoker
    CodeUri: ./application
    Tags:
      Stage: !Ref Stage
      Service: Tekbyte
      Resource: Lambda
    Environment:
      Variables:
        TABLE: !Ref TekbyteTable
        APPLICATION_ENVIRONMENT: !Ref Stage
        CLOUD_REGION: us-east-1
        MAIN_CLASS: com.tekcapsule.tekbyte.application.TekbyteApplication
        JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1

Resources:

  # Setup API Gateway

  TekbyteApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub "tekbyte-${Stage}"
      StageName: !Ref Stage
      Cors:
        AllowMethods: "'POST, GET'"
        AllowHeaders: "'X-Forwarded-For, Content-Type, Authorization, X-User-Login, X-Channel-Code'"
        AllowOrigin: "'*'"
        MaxAge: "'600'"
        AllowCredentials: false
      Variables:
        LAMBDA_ALIAS: !Ref Stage

  # Setup DynamoDB Table

  TekbyteTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${Stage}Tekbyte"
      AttributeDefinitions:
        - AttributeName: code
          AttributeType: S
      KeySchema:
        - AttributeName: code
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

  RecommendTekbyteFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${Stage}-Tekbyte-RecommendTekbyte"
      SnapStart:
        ApplyOn: PublishedVersions
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TekbyteTable
      Environment:
        Variables:
          SPRING_CLOUD_FUNCTION_DEFINITION: recommendFunction
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: tekbyte/recommend
            Method: post
            RestApiId:
              Ref: TekbyteApi

  # Setup Lambda Functions

  CreateTekbyteFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${Stage}-Tekbyte-CreateTekbyte"
      SnapStart:
        ApplyOn: PublishedVersions
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TekbyteTable
      Environment:
        Variables:
          SPRING_CLOUD_FUNCTION_DEFINITION: createFunction
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: tekbyte/create
            Method: post
            RestApiId:
              Ref: TekbyteApi

  UpdateTekbyteFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${Stage}-Tekbyte-UpdateTekbyte"
      SnapStart:
        ApplyOn: PublishedVersions
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TekbyteTable
      Environment:
        Variables:
          SPRING_CLOUD_FUNCTION_DEFINITION: updateFunction
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: tekbyte/update
            Method: post
            RestApiId:
              Ref: TekbyteApi

  DisableTekbyteFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${Stage}-Tekbyte-DisableTekbyte"
      SnapStart:
        ApplyOn: PublishedVersions
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TekbyteTable
      Environment:
        Variables:
          SPRING_CLOUD_FUNCTION_DEFINITION: disableFunction
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: tekbyte/disable
            Method: post
            RestApiId:
              Ref: TekbyteApi

  GetTekbyteFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${Stage}-Tekbyte-GetTekbyte"
      SnapStart:
        ApplyOn: PublishedVersions
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TekbyteTable
      Environment:
        Variables:
          SPRING_CLOUD_FUNCTION_DEFINITION: getFunction
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: tekbyte/get
            Method: post
            RestApiId:
              Ref: TekbyteApi

  GetAllTekbytesFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${Stage}-Tekbyte-GetAllTekbytes"
      SnapStart:
        ApplyOn: PublishedVersions
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TekbyteTable
      Environment:
        Variables:
          SPRING_CLOUD_FUNCTION_DEFINITION: getAllFunction
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: tekbyte/getAll
            Method: post
            RestApiId:
              Ref: TekbyteApi

  GetTekbytesCountFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${Stage}-Tekbyte-GetTekbytesCount"
      SnapStart:
        ApplyOn: PublishedVersions
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TekbyteTable
      Environment:
        Variables:
          SPRING_CLOUD_FUNCTION_DEFINITION: getCountFunction
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: tekbyte/getCount
            Method: post
            RestApiId:
              Ref: TekbyteApi

  # Set Output Variable

Outputs:
  ApiEndpoint:
    Description: "Tekbyte API endpoint."
    Value: !Sub "https://${TekbyteApi}.execute-api.${AWS::Region}.amazonaws.com/${Stage}/tekbyte"